/**
 * The Paddle SANDBOX end-to-end proof, against the LOCAL stack (owner ruling 31.08.2026, option ב).
 *
 * WHAT MAKES THIS DIFFERENT FROM p71. p71 proves the transitions with payloads this repository
 * wrote, inside a transaction, with no network. It is the right test and it stays. What it cannot
 * prove is that PADDLE's real bytes verify against OUR real HMAC over a real HTTP request -- which
 * is exactly the half that has broken silently before in this codebase (`gateway_contract_mismatch`,
 * five days of documents "waiting in queue"). So every event below is generated by Paddle, signed
 * by Paddle, and delivered by Paddle over the internet to billing-webhook running the deployed
 * source. Nothing here fabricates a signature.
 *
 * WHY IT RUNS AGAINST THE LOCAL STACK AND NOT PRODUCTION. Proving an ACTIVATION means the merchant
 * of record has to be enabled, and enabling it in production would be switching on real billing --
 * which the owner explicitly excluded. So the provider is enabled here, in a local database, by
 * this script, and switched off again in its `finally`. No migration carries that enable, nothing
 * permanent is added, and production's boundary is untouched and still shut.
 *
 * WHAT IT STILL CANNOT PROVE, AND SAYS SO. A real card payment. Paddle refuses
 * `POST /transactions` with `transaction_default_checkout_url_not_set` until a default payment link
 * is set in the Paddle dashboard, which is not an API surface. Everything downstream of a payment
 * is proven here from Paddle's own signed events; the payment itself is a dashboard step recorded
 * as a blocker rather than quietly skipped.
 *
 * PREREQUISITES (see docs/PADDLE-SANDBOX.md):
 *   * billing-webhook served locally and reachable at a public https URL
 *   * that URL registered with sandbox-notification-destination.mjs
 *   * the local Supabase stack up
 *
 * Usage: node scripts/paddle/sandbox-e2e.mjs
 */
import fs from 'node:fs';
import { execFileSync } from 'node:child_process';

const BASE = 'https://sandbox-api.paddle.com';
const KEY = fs.readFileSync('D:/משה פרוייקטים/פיתוח אתרים/AI/API/Sandbox API Key.txt', 'utf8').trim();
if (!KEY.startsWith('pdl_sdbx_')) throw new Error('refusing to run: not a Paddle SANDBOX key');
const HEADERS = { Authorization: `Bearer ${KEY}`, 'Content-Type': 'application/json', 'Paddle-Version': '1' };
const CONTAINER = process.env.PADDLE_PSQL_CONTAINER ?? 'supabase_db_supplyflow-p0';

// Two tenants. B is the bystander and exists for one reason: to be provably untouched.
const ORG_A = 'bb000000-0000-4000-8000-0000000000a1';
const ORG_B = 'bb000000-0000-4000-8000-0000000000b2';
const PRO_MONTHLY = 'pri_01m1c3fvr5wm54pw5rkdw09tyd';
const PREMIUM_MONTHLY = 'pri_01m1c3fwbrcb19f18hqh8jpfvn';
const BASIC_MONTHLY = 'pri_01m1c3fv4a08jwdvhhj9btmg6j';

const results = [];
const record = (name, pass, detail) => {
  results.push({ name, pass, detail });
  console.log(`${pass ? '  PASS' : '  FAIL'}  ${name}${detail ? ` — ${detail}` : ''}`);
};

function sql(query) {
  return execFileSync('docker', ['exec', '-i', CONTAINER, 'psql', '-U', 'postgres', '-d', 'postgres',
    '-At', '-F', '\t', '-v', 'ON_ERROR_STOP=1', '-c', query], { encoding: 'utf8' }).trim();
}
const sqlRows = (query) => sql(query).split(/\r?\n/).filter(Boolean).map((line) => line.split('\t'));
const sqlOne = (query) => sql(query);

async function api(method, path, body) {
  const response = await fetch(BASE + path, {
    method, headers: HEADERS, body: body === undefined ? undefined : JSON.stringify(body),
  });
  const text = await response.text();
  let parsed; try { parsed = JSON.parse(text); } catch { parsed = { raw: text.slice(0, 400) }; }
  return { status: response.status, body: parsed, ok: response.ok };
}

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

/** Waits for Paddle to finish delivering a simulation run, then returns its per-event outcomes. */
async function runSimulation(simulationId, label) {
  const started = await api('POST', `/simulations/${simulationId}/runs`, {});
  if (!started.ok) throw new Error(`${label}: could not start run — ${JSON.stringify(started.body.error)}`);
  const runId = started.body.data.id;

  for (let attempt = 0; attempt < 40; attempt += 1) {
    await sleep(1500);
    const run = await api('GET', `/simulations/${simulationId}/runs/${runId}?include=events`);
    if (!run.ok) continue;
    if (run.body.data.status !== 'pending') {
      return run.body.data.events ?? [];
    }
  }
  throw new Error(`${label}: the simulation run never completed`);
}

// ===========================================================================================
// Setup
// ===========================================================================================
console.log('=== setup ===');

// Two organizations that belong to this harness alone, so nothing it does can be mistaken for, or
// collide with, the demo tenant other suites depend on.
sql(`insert into organizations (id, name, status) values
       ('${ORG_A}', 'Paddle sandbox tenant A', 'active'),
       ('${ORG_B}', 'Paddle sandbox tenant B', 'active')
     on conflict (id) do nothing`);
sql(`update organization_subscriptions set plan_key = 'free', status = 'active',
       provider = 'manual', provider_customer_id = null, provider_subscription_id = null,
       current_period_start = null, current_period_end = null, renews_at = null, canceled_at = null
     where org_id in ('${ORG_A}', '${ORG_B}')`);
console.log(`  two tenants seeded on free/manual`);

// THE DESTINATION IS CHOSEN NARROWLY, AND THE NARROWNESS IS THE POINT. This sandbox account also
// holds a destination aimed at the PRODUCTION Edge Function, and an earlier draft of this line
// picked "the first active one whose URL contains /billing-webhook" -- which would have fired
// simulated subscription events at production. It is inert there today (no endpoint secret is set,
// and the boundary is shut), but a harness that CAN aim at production is a harness that eventually
// does. So anything hosted at supabase.co is refused outright, and the local tunnel is required.
const destinations = (await api('GET', '/notification-settings')).body.data
  .filter((row) => row.active && row.destination.includes('/billing-webhook'));
const destination = destinations.find((row) => !/\.supabase\.co\//.test(row.destination));
if (!destination) {
  throw new Error('no LOCAL billing-webhook destination is registered; this harness refuses to '
    + 'drive a deployed endpoint. Start the tunnel and run sandbox-notification-destination.mjs.');
}
if (destination.traffic_source !== 'all' && destination.traffic_source !== 'simulation') {
  await api('PATCH', `/notification-settings/${destination.id}`, { traffic_source: 'all' });
  console.log('  destination widened to accept simulation traffic');
}
console.log(`  destination      ${destination.destination}`);
for (const other of destinations.filter((row) => row.id !== destination.id)) {
  console.log(`  NOTE: another active destination exists and is NOT used here: ${other.destination}`);
}

// A real Paddle customer for tenant A, and the link WE write — the only thing attribution reads.
const emailA = `inplace-sandbox-a@inplace-sandbox.test`;
let customerA = (await api('GET', `/customers?email=${encodeURIComponent(emailA)}&per_page=2`)).body.data?.[0];
if (!customerA) {
  const created = await api('POST', '/customers', { email: emailA, custom_data: { inplace_org_id: ORG_A } });
  if (!created.ok) throw new Error(`could not create customer A: ${JSON.stringify(created.body.error)}`);
  customerA = created.body.data;
} else if (customerA.status === 'archived') {
  customerA = (await api('PATCH', `/customers/${customerA.id}`, { status: 'active' })).body.data;
}
console.log(`  customer A       ${customerA.id}`);

sql(`select public.service_link_billing_customer('${ORG_A}', 'paddle', '${customerA.id}')`);
record('customer-to-org link written by InPlace',
  sqlOne(`select provider_customer_id from organization_subscriptions where org_id = '${ORG_A}'`) === customerA.id);

// THE ENABLE. Local, temporary, and reversed in the finally below. Nothing in a migration does this.
sql(`update private.billing_provider_boundary
       set enabled = true, enabled_at = now(),
           enabled_by = (select id from auth.users order by created_at limit 1),
           enable_reason = 'sandbox-e2e.mjs; reversed by the same script'
     where provider = 'paddle'`);
console.log('  paddle ENABLED locally (temporary)');

let exitCode = 0;
try {
  // =========================================================================================
  // 1. Signature verification and attribution, on Paddle's own bytes
  // =========================================================================================
  console.log('\n=== 1. a real signed activation reaches the right tenant ===');

  const before = Number(sqlOne('select count(*) from private.billing_events'));

  const activation = await api('POST', '/simulations', {
    notification_setting_id: destination.id,
    name: `inplace-e2e activation ${Date.now()}`,
    type: 'subscription.activated',
    // The simulation is built around OUR customer and OUR mapped price, so the event that arrives
    // is attributable and its price resolves to a plan. Both are facts the database decides.
    payload: {
      customer_id: customerA.id,
      status: 'active',
      billing_cycle: { interval: 'month', frequency: 1 },
      current_billing_period: {
        starts_at: '2026-08-31T00:00:00Z',
        ends_at: '2026-09-30T00:00:00Z',
      },
      next_billed_at: '2026-09-30T00:00:00Z',
      items: [{ price: { id: PRO_MONTHLY }, quantity: 1 }],
    },
  });
  if (!activation.ok) throw new Error(`could not create simulation: ${JSON.stringify(activation.body.error)}`);
  const activationEvents = await runSimulation(activation.body.data.id, 'activation');

  const delivered = activationEvents.filter((event) => event.status === 'success');
  record('Paddle delivered and our endpoint accepted it',
    delivered.length > 0,
    `${delivered.length}/${activationEvents.length} events accepted (200)`);

  const stored = Number(sqlOne('select count(*) from private.billing_events')) - before;
  record('the delivery was recorded in the event ledger', stored > 0, `${stored} new row(s)`);

  const planA = sqlOne(`select plan_key from organization_subscriptions where org_id = '${ORG_A}'`);
  record('entitlement moved to the mapped plan, from a signed event alone',
    planA === 'pro', `tenant A is on '${planA}'`);

  const planB = sqlOne(`select plan_key from organization_subscriptions where org_id = '${ORG_B}'`);
  record('TENANT ISOLATION: the bystander is untouched', planB === 'free', `tenant B is on '${planB}'`);

  // =========================================================================================
  // 2. Idempotency — the same event id, delivered again
  // =========================================================================================
  console.log('\n=== 2. a redelivery is one effect ===');

  const eventRow = sqlRows(`select provider_event_id, status from private.billing_events
                            where org_id = '${ORG_A}' order by received_at desc limit 1`)[0];
  if (eventRow) {
    const [eventId] = eventRow;
    const applyAgain = sqlOne(`select public.service_apply_billing_event('paddle', '${eventId}')`);
    record('re-applying a processed event is idempotent and applies nothing',
      applyAgain.includes('"idempotent": true') || applyAgain.includes('"idempotent":true'),
      applyAgain.slice(0, 120));
    record('the ledger still holds exactly one row for that event id',
      Number(sqlOne(`select count(*) from private.billing_events where provider_event_id = '${eventId}'`)) === 1);
  }

  // =========================================================================================
  // 2b. Upgrade and downgrade — #216, the provider is authoritative for which rung is live
  // =========================================================================================
  // We do NOT keep our own schedule for a tier change. #216 says the change lands at the next
  // renewal with no proration, so whatever the provider reports as the CURRENT price IS the change
  // having arrived. `subscription.updated` carrying a different mapped price is therefore the whole
  // mechanism, and both directions are the same code path — which is exactly why both are checked:
  // a downgrade that silently kept the higher rung would be indistinguishable from a working
  // upgrade until a customer noticed they were being billed for less than they had.
  console.log('\n=== 2b. plan change in both directions ===');

  for (const move of [
    { label: 'upgrade   pro -> premium', priceId: PREMIUM_MONTHLY, expect: 'premium' },
    { label: 'downgrade premium -> basic', priceId: BASIC_MONTHLY, expect: 'basic' },
  ]) {
    const updated = await api('POST', '/simulations', {
      notification_setting_id: destination.id,
      name: `inplace-e2e ${move.expect} ${Date.now()}`,
      type: 'subscription.updated',
      payload: {
        customer_id: customerA.id,
        status: 'active',
        billing_cycle: { interval: 'month', frequency: 1 },
        current_billing_period: { starts_at: '2026-08-31T00:00:00Z', ends_at: '2026-09-30T00:00:00Z' },
        next_billed_at: '2026-09-30T00:00:00Z',
        items: [{ price: { id: move.priceId }, quantity: 1 }],
      },
    });
    if (!updated.ok) {
      record(move.label, false, JSON.stringify(updated.body.error).slice(0, 160));
      continue;
    }
    await runSimulation(updated.body.data.id, move.label);
    const landed = sqlOne(`select plan_key from organization_subscriptions where org_id = '${ORG_A}'`);
    record(`${move.label} (#216, from a signed subscription.updated)`,
      landed === move.expect, `tenant A is on '${landed}'`);
    record(`  and the bystander is untouched by the ${move.expect} move`,
      sqlOne(`select plan_key from organization_subscriptions where org_id = '${ORG_B}'`) === 'free');
  }

  // Put A back on pro so the cancellation below starts from a paid rung.
  sql(`update organization_subscriptions set plan_key = 'pro' where org_id = '${ORG_A}'`);

  // =========================================================================================
  // 3. Cancellation — #219, at the period boundary
  // =========================================================================================
  console.log('\n=== 3. cancellation ===');

  const cancellation = await api('POST', '/simulations', {
    notification_setting_id: destination.id,
    name: `inplace-e2e cancel ${Date.now()}`,
    type: 'subscription.canceled',
    payload: {
      customer_id: customerA.id,
      status: 'canceled',
      billing_cycle: { interval: 'month', frequency: 1 },
      items: [{ price: { id: PRO_MONTHLY }, quantity: 1 }],
    },
  });
  if (cancellation.ok) {
    await runSimulation(cancellation.body.data.id, 'cancellation');
    const planAfter = sqlOne(`select plan_key from organization_subscriptions where org_id = '${ORG_A}'`);
    record('a signed cancellation returns the tenant to Free (#219/#220)',
      planAfter === 'free', `tenant A is on '${planAfter}'`);
    record('and the bystander is STILL untouched',
      sqlOne(`select plan_key from organization_subscriptions where org_id = '${ORG_B}'`) === 'free');
  } else {
    record('cancellation simulation created', false, JSON.stringify(cancellation.body.error).slice(0, 200));
  }

  // =========================================================================================
  // 4. Past due — #221, read-only rather than deletion
  // =========================================================================================
  console.log('\n=== 4. payment failure ===');

  sql(`update organization_subscriptions set plan_key = 'pro', status = 'active'
       where org_id = '${ORG_A}'`);
  const pastDue = await api('POST', '/simulations', {
    notification_setting_id: destination.id,
    name: `inplace-e2e pastdue ${Date.now()}`,
    type: 'subscription.past_due',
    payload: {
      customer_id: customerA.id,
      status: 'past_due',
      billing_cycle: { interval: 'month', frequency: 1 },
      items: [{ price: { id: PRO_MONTHLY }, quantity: 1 }],
    },
  });
  if (pastDue.ok) {
    await runSimulation(pastDue.body.data.id, 'past_due');
    const status = sqlOne(`select status from organization_subscriptions where org_id = '${ORG_A}'`);
    record('a failed renewal marks the tenant delinquent, not deleted (#221)',
      status === 'past_due', `status '${status}'`);
    record('and the plan is NOT silently downgraded',
      sqlOne(`select plan_key from organization_subscriptions where org_id = '${ORG_A}'`) === 'pro');
  }

  // =========================================================================================
  // 5. The failure modes that must stay visible
  // =========================================================================================
  console.log('\n=== 5. unknown customer, unknown price, forged tenant ===');

  // An event naming a provider customer nobody is linked to. It must dead-letter as unattributable
  // and touch no tenant at all.
  const unknownCustomer = sqlOne(`select public.service_record_billing_event(
    'paddle', 'evt_e2e_unknown_customer_${Date.now()}', 'subscription.activated',
    'ctm_nobody_is_linked_to_this', '{"data":{"customer_id":"ctm_nobody_is_linked_to_this"}}'::jsonb)`);
  record('an unknown provider customer dead-letters and is visible for reconciliation',
    unknownCustomer.includes('dead_letter'), unknownCustomer.slice(0, 120));

  // An event for OUR customer naming a price nobody mapped. It is attributable, so it must NOT be
  // silently ignored -- it must dead-letter with a reason a person can work.
  const unmappedId = `evt_e2e_unmapped_${Date.now()}`;
  sql(`select public.service_record_billing_event('paddle', '${unmappedId}', 'subscription.activated',
        '${customerA.id}', '{"data":{"customer_id":"${customerA.id}",
        "billing_cycle":{"interval":"month"},"items":[{"price":{"id":"pri_never_mapped_anywhere"}}]}}'::jsonb)`);
  sql(`select public.service_apply_billing_event('paddle', '${unmappedId}')`);
  const unmappedReason = sqlOne(`select reason_code from private.billing_event_dead_letters
    where billing_event_id = (select id from private.billing_events where provider_event_id = '${unmappedId}')`);
  record('an unmapped price fails safe and stays visible, granting nothing',
    unmappedReason === 'plan_unmapped', `reason '${unmappedReason}'`);

  // THE ATTACK. An event that names tenant B in every payload field an attacker can reach, while
  // its provider customer id resolves to nobody.
  const forgedId = `evt_e2e_forged_${Date.now()}`;
  const planBBefore = sqlOne(`select plan_key from organization_subscriptions where org_id = '${ORG_B}'`);
  sql(`select public.service_record_billing_event('paddle', '${forgedId}', 'subscription.activated',
        'ctm_not_ours_at_all', jsonb_build_object('data', jsonb_build_object(
          'customer_id', 'ctm_not_ours_at_all',
          'custom_data', jsonb_build_object('org_id', '${ORG_B}'),
          'passthrough', '{"org_id":"${ORG_B}"}',
          'metadata', jsonb_build_object('org_id', '${ORG_B}'),
          'items', jsonb_build_array(jsonb_build_object('price', jsonb_build_object('id', '${PRO_MONTHLY}'))),
          'billing_cycle', jsonb_build_object('interval', 'month'))))`);
  const planBAfter = sqlOne(`select plan_key from organization_subscriptions where org_id = '${ORG_B}'`);
  record('TENANT ISOLATION: a payload naming org B in custom_data/passthrough/metadata changes nothing',
    planBAfter === planBBefore && planBAfter === 'free',
    `org B before '${planBBefore}', after '${planBAfter}'`);

  // =========================================================================================
  // 6. An invalid signature never changes state
  // =========================================================================================
  console.log('\n=== 6. an invalid signature ===');

  const planBeforeForgery = sqlOne(`select plan_key from organization_subscriptions where org_id = '${ORG_A}'`);
  const forgery = await fetch(destination.destination, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Paddle-Signature': `ts=${Math.floor(Date.now() / 1000)};h1=${'0'.repeat(64)}` },
    body: JSON.stringify({
      event_id: `evt_e2e_forged_signature_${Date.now()}`,
      event_type: 'subscription.activated',
      data: { customer_id: customerA.id, items: [{ price: { id: PRO_MONTHLY } }], billing_cycle: { interval: 'month' } },
    }),
  });
  record('a wrong signature is refused at the door', forgery.status === 403, `HTTP ${forgery.status}`);
  record('and it changed no subscription state',
    sqlOne(`select plan_key from organization_subscriptions where org_id = '${ORG_A}'`) === planBeforeForgery);
  record('and it was NOT written to the event ledger (the ledger stays unpoisonable)',
    Number(sqlOne(`select count(*) from private.billing_events where provider_event_id like 'evt_e2e_forged_signature_%'`)) === 0);

  // A replayed timestamp: correctly formed, far outside the tolerance window.
  const stale = await fetch(destination.destination, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Paddle-Signature': `ts=${Math.floor(Date.now() / 1000) - 3600};h1=${'a'.repeat(64)}` },
    body: JSON.stringify({ event_id: 'evt_e2e_stale', event_type: 'subscription.activated', data: {} }),
  });
  record('REPLAY PROTECTION: a stale timestamp is refused', stale.status === 403, `HTTP ${stale.status}`);

  record('every refusal was counted for the operator without storing caller-supplied ids',
    Number(sqlOne(`select count(*) from private.billing_ingress_rejections
                   where occurred_at > now() - interval '10 minutes'`)) >= 2);

} finally {
  // =========================================================================================
  // Teardown — the enable is reversed whatever happened above
  // =========================================================================================
  console.log('\n=== teardown ===');
  sql(`update private.billing_provider_boundary
         set enabled = false, enabled_at = null, enabled_by = null, enable_reason = null
       where provider = 'paddle'`);
  const stillEnabled = sqlOne('select count(*) from private.billing_provider_boundary where enabled');
  console.log(`  paddle disabled again (providers enabled: ${stillEnabled})`);
  if (stillEnabled !== '0') {
    console.error('  !! a provider is still enabled — fix before leaving this stack');
    exitCode = 1;
  }

  /*
   * AND THE ROWS GO TOO, because `supplyflow-p0` is a shared stack.
   *
   * This is not tidiness. Everything above writes to tables OTHER suites read, outside any
   * transaction, and the first run of this harness broke p71: it asserted an absolute
   * `count(*) = 1` on private.billing_ingress_rejections, and real refused deliveries from here
   * made it 5. p71's assertion is now a delta — which it should always have been — but that fixes
   * one suite, not the general problem of a harness that drives a live endpoint and walks away
   * having changed a database another agent is mid-gate on.
   *
   * Deletions are scoped to what this file created: its own two organizations, and the events and
   * dead letters attributable to them or minted by its own `evt_e2e_` prefix. The ingress
   * rejections cannot be scoped that way — they deliberately carry no caller-supplied identifier
   * (that is the whole point of 0187's counter) — so they are cleared by recency instead, which is
   * the closest honest approximation and is stated rather than hidden.
   */
  sql(`delete from private.billing_event_dead_letters
       where billing_event_id in (select id from private.billing_events
                                  where provider_event_id like 'evt_e2e_%'
                                     or org_id in ('${ORG_A}', '${ORG_B}'))`);
  sql(`delete from private.billing_events
       where provider_event_id like 'evt_e2e_%' or org_id in ('${ORG_A}', '${ORG_B}')`);
  sql(`delete from private.billing_ingress_rejections
       where occurred_at > now() - interval '1 hour'`);
  sql(`delete from private.subscription_scheduled_changes where org_id in ('${ORG_A}', '${ORG_B}')`);

  /*
   * THE TWO ORGANIZATIONS STAY, AND SO DO THEIR AUDIT ROWS. An earlier version of this teardown
   * tried to delete both and was refused by private.audit_log_immutable_guard() with
   * `audit_log_immutable` — audit rows cannot be deleted without a declared purge, by design and
   * correctly. Since audit_logs references the organization, the organization cannot go either.
   *
   * That refusal is worth more than a clean row count, so it is honoured rather than worked
   * around: the two tenants are named "Paddle sandbox tenant A/B", they are inert (Free, manual
   * provider, no provider link), and they cost a shared dev database nothing. What is actually
   * cleaned is what actually broke something — the event ledger and the rejection counter.
   */
  sql(`update organization_subscriptions
          set plan_key = 'free', status = 'active', provider = 'manual',
              provider_customer_id = null, provider_subscription_id = null,
              current_period_start = null, current_period_end = null,
              renews_at = null, canceled_at = null
        where org_id in ('${ORG_A}', '${ORG_B}')`);

  const leftovers = sqlOne(
    `select (select count(*) from private.billing_events
             where provider_event_id like 'evt_e2e_%' or org_id in ('${ORG_A}', '${ORG_B}'))::text`);
  console.log(`  harness billing rows removed (events remaining: ${leftovers});`
    + ' the two inert tenants and their immutable audit rows remain, by design');
  if (leftovers !== '0') {
    console.error('  !! this harness left billing rows behind in a SHARED stack — clean before handoff');
    exitCode = 1;
  }
}

console.log('\n=== summary ===');
const failed = results.filter((row) => !row.pass);
console.log(`${results.length - failed.length}/${results.length} checks passed`);
for (const row of failed) console.log(`  FAILED: ${row.name} — ${row.detail ?? ''}`);
process.exit(failed.length > 0 ? 1 : exitCode);
