import {
  ScenarioDefinitionSchema,
  type ScenarioDefinition,
  type ScenarioId,
} from './schema.ts';

const definitions = [
  {
    id: 'supplier-price-list',
    sequence: 1,
    title: 'Supplier price-list submission',
    purpose: 'Prove that the canonical supplier can submit a synthetic price list through the controlled document intake without gaining tenant-wide access.',
    roles: ['supplier'],
    status: 'READY',
    viewport: 'both',
    fixtures: ['demo-seed', 'price-list-xlsx'],
    dependsOn: [],
    routeExpectations: [{
      role: 'supplier',
      allowed: ['/dashboard', '/my-prices', '/documents/:documentId/review'],
      forbidden: ['/suppliers', '/orders', '/payment-requests', '/pay', '/bank', '/settings', '/admin'],
    }],
    steps: [
      {
        id: 'open-supplier-portal',
        actorRole: 'supplier',
        route: '/my-prices',
        action: 'Open the supplier portal and confirm that only the linked supplier catalog is visible.',
        expected: 'The current supplier prices load without data belonging to another supplier or tenant.',
        verifierIds: ['authorization', 'database'],
        mutatesData: false,
      },
      {
        id: 'submit-price-workbook',
        actorRole: 'supplier',
        route: '/my-prices',
        action: 'Upload the run-scoped XLSX, review recognized rows, enter month and reason, then confirm once.',
        expected: 'A document-backed submission receipt is shown and every accepted price references a canonical product.',
        verifierIds: ['database', 'data-integrity', 'audit'],
        mutatesData: true,
      },
      {
        id: 'replay-price-workbook',
        actorRole: 'supplier',
        route: '/my-prices',
        action: 'Retry the same upload once to exercise idempotency and recovery messaging.',
        expected: 'The system does not duplicate the financial price mutation and presents a safe recoverable result.',
        verifierIds: ['database', 'data-integrity', 'audit'],
        mutatesData: true,
      },
    ],
    verifierIds: ['authorization', 'database', 'data-integrity', 'audit'],
    evidence: ['screenshot', 'action-trace', 'network', 'database', 'audit'],
    maxAgentSteps: 30,
    maxRetries: 2,
  },
  {
    id: 'kitchen-receiving',
    sequence: 2,
    title: 'Kitchen goods receiving',
    purpose: 'Prove partial receiving and discrepancy capture against an existing open purchase order.',
    roles: ['kitchen'],
    status: 'READY',
    viewport: 'both',
    fixtures: ['demo-seed', 'receipt-jpg'],
    dependsOn: [],
    routeExpectations: [{
      role: 'kitchen',
      allowed: ['/dashboard', '/orders', '/receiving', '/invoices', '/documents'],
      forbidden: ['/payment-requests', '/payments', '/pay', '/bank', '/reports', '/audit', '/settings', '/admin'],
    }],
    steps: [
      {
        id: 'select-open-order',
        actorRole: 'kitchen',
        route: '/receiving',
        action: 'Select a demo order that still has receivable quantity.',
        expected: 'The order and remaining quantities are visible and belong to the active organization.',
        verifierIds: ['authorization', 'database'],
        mutatesData: false,
      },
      {
        id: 'record-partial-receipt',
        actorRole: 'kitchen',
        route: '/receiving/:orderId',
        action: 'Record run-scoped partial quantities, a discrepancy note, reason, and the synthetic receipt image.',
        expected: 'Exactly one receipt is created, order item received quantities are updated, and the document path begins with org_id.',
        verifierIds: ['database', 'data-integrity', 'audit'],
        mutatesData: true,
      },
    ],
    verifierIds: ['authorization', 'database', 'data-integrity', 'audit'],
    evidence: ['screenshot', 'action-trace', 'network', 'database', 'audit'],
    maxAgentSteps: 30,
    maxRetries: 2,
  },
  {
    id: 'office-invoice-review',
    sequence: 3,
    title: 'Office invoice review',
    purpose: 'Prove invoice entry and review against purchase/receipt context while preserving computed balances.',
    roles: ['office'],
    status: 'READY',
    viewport: 'both',
    fixtures: ['demo-seed', 'invoice-pdf'],
    dependsOn: ['kitchen-receiving'],
    routeExpectations: [{
      role: 'office',
      allowed: ['/dashboard', '/invoices', '/invoices/new', '/documents', '/payment-requests', '/analytics'],
      forbidden: ['/payments', '/pay', '/bank', '/reports', '/audit', '/settings', '/admin'],
    }],
    steps: [
      {
        id: 'create-invoice',
        actorRole: 'office',
        route: '/invoices/new',
        action: 'Create a run-scoped invoice for the selected supplier and attach the synthetic PDF.',
        expected: 'The invoice and document are stored once with the correct org/supplier relationship and org-prefixed storage path.',
        verifierIds: ['database', 'data-integrity', 'audit'],
        mutatesData: true,
      },
      {
        id: 'review-invoice-checks',
        actorRole: 'office',
        route: '/invoices/:id',
        action: 'Review purchase, receipt, duplicate, and payment signals and continue only through visible permitted actions.',
        expected: 'Decision signals use live data; missing values render as unavailable rather than invented zeroes.',
        verifierIds: ['database', 'data-integrity'],
        mutatesData: false,
      },
      {
        id: 'request-payment',
        actorRole: 'office',
        route: '/payment-requests',
        action: 'Create a payment request linked to the reviewed invoice with a run-scoped reason.',
        expected: 'The request links to the same-tenant invoice and supplier and produces a reasoned audit entry.',
        verifierIds: ['database', 'data-integrity', 'audit'],
        mutatesData: true,
      },
    ],
    verifierIds: ['authorization', 'database', 'data-integrity', 'audit'],
    evidence: ['screenshot', 'action-trace', 'network', 'database', 'audit'],
    maxAgentSteps: 30,
    maxRetries: 2,
  },
  {
    id: 'owner-payment-approval',
    sequence: 4,
    title: 'Owner payment-request approval',
    purpose: 'Prove the owner approval path, including mandatory reason and server-owned financial transition.',
    roles: ['owner'],
    status: 'READY',
    viewport: 'both',
    fixtures: ['demo-seed'],
    dependsOn: ['office-invoice-review'],
    routeExpectations: [{
      role: 'owner',
      allowed: ['/dashboard', '/payment-requests', '/payments', '/pay/emergency', '/bank', '/reports', '/audit', '/settings'],
      forbidden: ['/pay', '/my-prices', '/admin'],
    }],
    steps: [
      {
        id: 'inspect-payment-request',
        actorRole: 'owner',
        route: '/payment-requests',
        action: 'Open the run-scoped pending request and inspect supplier, invoice, amount, and decision context.',
        expected: 'The request uses live same-tenant data and cannot expose another organization.',
        verifierIds: ['authorization', 'database'],
        mutatesData: false,
      },
      {
        id: 'approve-payment-request',
        actorRole: 'owner',
        route: '/payment-requests',
        action: 'Approve the request once with a run-scoped reason.',
        expected: 'The server transitions the request to approved and records approver, timestamp, and reason in audit.',
        verifierIds: ['database', 'data-integrity', 'audit'],
        mutatesData: true,
      },
    ],
    verifierIds: ['authorization', 'database', 'data-integrity', 'audit'],
    evidence: ['screenshot', 'action-trace', 'network', 'database', 'audit'],
    maxAgentSteps: 24,
    maxRetries: 2,
  },
  {
    id: 'payer-transfer-execution',
    sequence: 5,
    title: 'Payer transfer execution',
    purpose: 'Prove execution of an approved request by the payer without access to broader accounting or procurement data.',
    roles: ['payer'],
    status: 'READY',
    viewport: 'both',
    fixtures: ['demo-seed'],
    dependsOn: ['owner-payment-approval'],
    routeExpectations: [{
      role: 'payer',
      allowed: ['/dashboard', '/pay'],
      forbidden: ['/suppliers', '/orders', '/receiving', '/invoices', '/payment-requests', '/payments', '/bank', '/reports', '/audit', '/settings', '/admin'],
    }],
    steps: [
      {
        id: 'open-approved-queue',
        actorRole: 'payer',
        route: '/pay',
        action: 'Open the approved transfer queue and select the run-scoped request.',
        expected: 'Only requests eligible for execution are shown; unrelated financial details remain inaccessible.',
        verifierIds: ['authorization', 'database'],
        mutatesData: false,
      },
      {
        id: 'execute-transfer',
        actorRole: 'payer',
        route: '/pay',
        action: 'Record the transfer once using the run-scoped reference and mandatory reason.',
        expected: 'One payment and its N:M allocations are created, the request advances, and invoice balance is computed from allocations.',
        verifierIds: ['database', 'data-integrity', 'audit'],
        mutatesData: true,
      },
      {
        id: 'retry-transfer',
        actorRole: 'payer',
        route: '/pay',
        action: 'Retry the same execution once after the success response.',
        expected: 'The server rejects or idempotently resolves the replay without creating a duplicate payment.',
        verifierIds: ['database', 'data-integrity', 'audit'],
        mutatesData: true,
      },
    ],
    verifierIds: ['authorization', 'database', 'data-integrity', 'audit'],
    evidence: ['screenshot', 'action-trace', 'network', 'database', 'audit'],
    maxAgentSteps: 28,
    maxRetries: 2,
  },
  {
    id: 'accountant-reconciliation',
    sequence: 6,
    title: 'Accountant bank reconciliation and reporting',
    purpose: 'Prove bank import, matching, and deterministic monthly reporting against the executed payment.',
    roles: ['accountant'],
    status: 'READY',
    viewport: 'both',
    fixtures: ['demo-seed', 'bank-csv'],
    dependsOn: ['payer-transfer-execution'],
    routeExpectations: [{
      role: 'accountant',
      allowed: ['/dashboard', '/invoices', '/payments', '/pay', '/bank', '/expenses', '/reports', '/audit', '/analytics'],
      forbidden: ['/suppliers', '/products', '/prices', '/orders', '/receiving', '/documents', '/payment-requests', '/settings', '/my-prices', '/admin'],
    }],
    steps: [
      {
        id: 'import-bank-csv',
        actorRole: 'accountant',
        route: '/bank',
        action: 'Import the run-scoped bank CSV, map required columns, and provide an import reason.',
        expected: 'Exactly one run-scoped transaction is imported with its source hash and same-tenant ownership.',
        verifierIds: ['database', 'data-integrity', 'audit'],
        mutatesData: true,
      },
      {
        id: 'match-bank-payment',
        actorRole: 'accountant',
        route: '/bank',
        action: 'Match the imported transaction to the executed payment with a reason.',
        expected: 'The N:M bank allocation, transaction state, and reasoned audit entry agree with the payment amount.',
        verifierIds: ['database', 'data-integrity', 'audit'],
        mutatesData: true,
      },
      {
        id: 'export-monthly-report',
        actorRole: 'accountant',
        route: '/reports',
        action: 'Generate and download the available monthly report formats for the run month.',
        expected: 'Downloads open successfully and contain headers, rows, and totals consistent with database evidence.',
        verifierIds: ['database', 'export'],
        mutatesData: false,
      },
    ],
    verifierIds: ['authorization', 'database', 'data-integrity', 'audit', 'export'],
    evidence: ['screenshot', 'action-trace', 'network', 'database', 'audit', 'download'],
    maxAgentSteps: 30,
    maxRetries: 2,
  },
  {
    id: 'authorization-matrix',
    sequence: 7,
    title: 'Full tenant-role authorization matrix',
    purpose: 'Prove allowed routes and representative denied routes for all six canonical tenant roles, including server-side denial evidence.',
    roles: ['all'],
    status: 'READY',
    viewport: 'desktop',
    fixtures: ['demo-seed'],
    dependsOn: [],
    routeExpectations: [
      { role: 'owner', allowed: ['/dashboard', '/suppliers', '/orders', '/receiving', '/invoices', '/payment-requests', '/payments', '/bank', '/reports', '/audit', '/settings'], forbidden: ['/pay', '/my-prices', '/admin'] },
      { role: 'office', allowed: ['/dashboard', '/suppliers', '/orders', '/receiving', '/invoices', '/documents', '/payment-requests', '/analytics'], forbidden: ['/pay', '/payments', '/bank', '/reports', '/audit', '/settings', '/admin'] },
      { role: 'kitchen', allowed: ['/dashboard', '/orders', '/receiving', '/invoices', '/documents'], forbidden: ['/payment-requests', '/pay', '/payments', '/bank', '/reports', '/audit', '/settings', '/admin'] },
      { role: 'payer', allowed: ['/dashboard', '/pay'], forbidden: ['/suppliers', '/orders', '/receiving', '/invoices', '/payment-requests', '/payments', '/bank', '/reports', '/audit', '/settings', '/admin'] },
      { role: 'accountant', allowed: ['/dashboard', '/invoices', '/payments', '/pay', '/bank', '/reports', '/audit', '/analytics'], forbidden: ['/suppliers', '/orders', '/receiving', '/documents', '/payment-requests', '/settings', '/admin'] },
      { role: 'supplier', allowed: ['/dashboard', '/my-prices', '/documents/:documentId/review'], forbidden: ['/suppliers', '/orders', '/invoices', '/payment-requests', '/pay', '/payments', '/bank', '/reports', '/audit', '/settings', '/admin'] },
    ],
    steps: [
      {
        id: 'verify-route-matrix',
        actorRole: 'owner',
        route: '/dashboard',
        action: 'For every canonical storage state, visit each allowed and forbidden representative route in a fresh page.',
        expected: 'Allowed routes render role-appropriate content; forbidden routes redirect or deny without unauthorized data.',
        verifierIds: ['authorization'],
        mutatesData: false,
      },
      {
        id: 'verify-server-denials',
        actorRole: 'owner',
        route: '/dashboard',
        action: 'Replay representative forbidden reads/mutations using the corresponding role session without changing request payloads.',
        expected: 'RLS/RPC boundaries deny the action and service-role SELECT-only verification proves no data mutation occurred.',
        verifierIds: ['authorization', 'database', 'static-security'],
        mutatesData: false,
      },
    ],
    verifierIds: ['authorization', 'database', 'static-security'],
    evidence: ['screenshot', 'action-trace', 'network', 'database'],
    maxAgentSteps: 60,
    maxRetries: 2,
  },
  {
    id: 'platform-admin',
    sequence: 8,
    title: 'Platform administration',
    purpose: 'Exercise the PlatformGuard and platform-only administration area only when an explicit isolated platform-admin fixture exists.',
    roles: ['platform'],
    status: 'BLOCKED',
    blockedReason: 'No approved local platform-admin Auth/profile fixture exists. Tenant owner credentials are not a substitute and must never be promoted by the QA runner.',
    viewport: 'both',
    fixtures: ['platform-admin-auth'],
    dependsOn: [],
    routeExpectations: [{
      role: 'platform',
      allowed: ['/admin'],
      forbidden: [],
    }],
    steps: [
      {
        id: 'verify-platform-admin',
        actorRole: 'platform',
        route: '/admin',
        action: 'Use a separately approved local platform-admin fixture to inspect platform controls.',
        expected: 'The route is accessible only to the platform fixture and no tenant role can enter it.',
        verifierIds: ['authorization', 'audit'],
        mutatesData: false,
      },
    ],
    verifierIds: ['authorization', 'audit'],
    evidence: ['screenshot', 'action-trace', 'network', 'audit'],
    maxAgentSteps: 20,
    maxRetries: 0,
  },
  {
    id: 'accessibility-keyboard',
    sequence: 9,
    title: 'Accessibility, keyboard, mobile RTL, and error recovery',
    purpose: 'Assess WCAG 2.1 AA automation signals plus keyboard and mobile usability on every core role journey without inventing a compliance claim.',
    roles: ['all'],
    status: 'READY',
    viewport: 'both',
    fixtures: ['demo-seed'],
    dependsOn: [],
    routeExpectations: [],
    steps: [
      {
        id: 'run-axe-core-routes',
        actorRole: 'owner',
        route: '/dashboard',
        action: 'Run axe-core after each core page reaches a stable loaded state for every role.',
        expected: 'Violations are captured with selectors and screenshots; automation does not claim full WCAG conformance.',
        verifierIds: ['accessibility'],
        mutatesData: false,
      },
      {
        id: 'keyboard-core-actions',
        actorRole: 'owner',
        route: '/dashboard',
        action: 'Navigate core controls using Tab, Shift+Tab, Enter, Space, Escape, and visible focus only.',
        expected: 'Focus order is logical in RTL, dialogs trap/restore focus, and critical actions never require hover.',
        verifierIds: ['accessibility', 'authorization'],
        mutatesData: false,
      },
      {
        id: 'mobile-rtl-recovery',
        actorRole: 'owner',
        route: '/dashboard',
        action: 'Repeat representative role tasks at mobile width and trigger safe validation/network recovery paths without submitting financial mutations.',
        expected: 'No horizontal clipping hides actions; errors are announced, understandable, and recoverable without duplicated submission.',
        verifierIds: ['accessibility'],
        mutatesData: false,
      },
    ],
    verifierIds: ['accessibility', 'authorization'],
    evidence: ['screenshot', 'action-trace', 'console', 'network', 'accessibility'],
    maxAgentSteps: 60,
    maxRetries: 2,
  },
] satisfies unknown[];

export const SCENARIOS: readonly ScenarioDefinition[] = Object.freeze(
  definitions.map((definition) => ScenarioDefinitionSchema.parse(definition)),
);

export const SCENARIO_IDS: readonly ScenarioId[] = Object.freeze(SCENARIOS.map(({ id }) => id));

export function getScenario(id: ScenarioId): ScenarioDefinition {
  const scenario = SCENARIOS.find((candidate) => candidate.id === id);
  if (!scenario) throw new Error(`Unknown QA scenario: ${id}`);
  return scenario;
}

export function getRunnableScenarios(): readonly ScenarioDefinition[] {
  return SCENARIOS.filter(({ status }) => status === 'READY');
}

export function getBlockedScenarios(): readonly ScenarioDefinition[] {
  return SCENARIOS.filter(({ status }) => status === 'BLOCKED');
}

export function assertScenarioRegistry(): void {
  if (SCENARIOS.length !== 9) throw new Error(`Expected 9 QA scenarios, found ${SCENARIOS.length}.`);
  const ids = new Set(SCENARIOS.map(({ id }) => id));
  const sequences = new Set(SCENARIOS.map(({ sequence }) => sequence));
  if (ids.size !== 9 || sequences.size !== 9) throw new Error('QA scenario ids and sequences must be unique.');
  const platform = getScenario('platform-admin');
  if (platform.status !== 'BLOCKED' || !platform.fixtures.includes('platform-admin-auth')) {
    throw new Error('Platform scenario must remain BLOCKED until its explicit fixture exists.');
  }
}

assertScenarioRegistry();
